In [2]:
distance=[10,20,30]
time=[5, 10, 15]
speed=distance/time
print(speed)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
import numpy as np

distance=[10,20,30]
time=[5, 6, 7]
dis=np.array(distance)
tim=np.array(time)
speed=dis/tim
print(speed)
print(type(dis))
print(type(tim))

[2.         3.33333333 4.28571429]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

a_rr= np.array([1,2,3,4])
print(a_rr)
print(a_rr.shape)
print(a_rr.ndim)

[1 2 3 4]
(4,)
1


In [ ]:
import numpy as np

a_rr= np.array([[1,2,3,4], [4,5,6,7]])
print(a_rr)
print(a_rr.shape)
print(a_rr.ndim)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)
2


In [ ]:
import numpy as np

a_rr= np.array([[[1,2,3,4], [4,5,6,7]], [[8,9,10, 11],[12,13,14,15]]])
print(a_rr)
print(a_rr.shape)
print(a_rr.ndim) 

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)
3


In [7]:
import numpy as np

a_rr= np.array([[1,2,3,4], [4,5,6,7]])
print(a_rr)
print("last element of 2 d array", a_rr[1, 2])
print("addition of the two element of aaray", a_rr[0, 1]+ a_rr[1, -1])
print("addition of 3 elemnt", a_rr[0, 1]+ a_rr[1, -4]+a_rr[1, -1] )

[[1 2 3 4]
 [4 5 6 7]]
last element of 2 d array 6
addition of the two element of aaray 9
addition of 3 elemnt 13


---------------------------------------------------------------------------------------------------------------------------

## <center>Slicing arrays</center>

        Slicing in python means taking elements from one given index to another given index.

        We pass slice instead of index like this: [start:end].

        We can also define the step, like this: [start:end:step].

        If we don't pass start its considered 0

        If we don't pass end its considered length of array in that dimension

        If we don't pass step its considered 1

---------------------------------------------------------------------------------------------------------------------------

In [39]:
import numpy as np

arr = np.array([[10, 20, 30],[ 40, 50, 60],[ 70, 80, 90]])

print(arr)
#print(arr[2::2 ])

print(arr[0:2:, 1:  ])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[20 30]]
